-- Generated by scripts/export_schema.py — do not edit.
-- Source of truth: convert_to_postgres.py

CREATE TABLE surahs (
    id INTEGER PRIMARY KEY,
    number INTEGER NOT NULL,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_en_translation TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('meccan', 'medinan', 'Meccan', 'Medinan')),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE juzs (
    id INTEGER PRIMARY KEY,
    juz_number INTEGER NOT NULL UNIQUE,
    name_ar TEXT NOT NULL,
    start_ayah_id INTEGER NOT NULL,
    end_ayah_id INTEGER NOT NULL
);

CREATE TABLE hizbs (
    id INTEGER PRIMARY KEY,
    hizb_number INTEGER NOT NULL UNIQUE,
    juz_id INTEGER NOT NULL REFERENCES juzs(id),
    name_ar TEXT NOT NULL,
    start_ayah_id INTEGER NOT NULL,
    end_ayah_id INTEGER NOT NULL
);

CREATE TABLE ayahs (
    id INTEGER PRIMARY KEY,
    number INTEGER NOT NULL,
    text TEXT NOT NULL,
    number_in_surah INTEGER NOT NULL,
    page INTEGER NOT NULL,
    surah_id INTEGER NOT NULL REFERENCES surahs(id),
    -- Quarter of a hizb (rub' al-hizb), 1-240. The source dump
    -- misnames this after the hizb, of which there are only 60.
    rub_id INTEGER NOT NULL CHECK(rub_id BETWEEN 1 AND 240),
    juz_id INTEGER NOT NULL REFERENCES juzs(id),
    sajda SMALLINT NOT NULL DEFAULT 0 CHECK(sajda IN (0, 1)),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE pages (
    id INTEGER PRIMARY KEY CHECK(id BETWEEN 1 AND 604),
    page_number INTEGER NOT NULL UNIQUE CHECK(page_number BETWEEN 1 AND 604),
    start_ayah_id INTEGER NOT NULL REFERENCES ayahs(id),
    end_ayah_id INTEGER NOT NULL REFERENCES ayahs(id),
    CHECK(start_ayah_id <= end_ayah_id)
);

CREATE TABLE editions (
    id INTEGER PRIMARY KEY,
    identifier TEXT NOT NULL UNIQUE,
    language TEXT NOT NULL,
    name TEXT NOT NULL,
    english_name TEXT NOT NULL,
    format TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE ayah_edition (
    id INTEGER PRIMARY KEY,
    ayah_id INTEGER NOT NULL REFERENCES ayahs(id),
    edition_id INTEGER NOT NULL REFERENCES editions(id),
    data TEXT NOT NULL,
    is_audio SMALLINT NOT NULL DEFAULT 0 CHECK(is_audio IN (0, 1)),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_ayahs_surah_id ON ayahs(surah_id);

CREATE INDEX idx_ayahs_juz_id ON ayahs(juz_id);

CREATE INDEX idx_ayahs_rub_id ON ayahs(rub_id);

CREATE INDEX idx_ayahs_page ON ayahs(page);

CREATE INDEX idx_ayahs_number_in_surah ON ayahs(surah_id, number_in_surah);

CREATE INDEX idx_ayahs_sajda ON ayahs(sajda) WHERE sajda = 1;

CREATE INDEX idx_ayah_edition_ayah ON ayah_edition(ayah_id);

CREATE INDEX idx_ayah_edition_edition ON ayah_edition(edition_id);

CREATE INDEX idx_ayah_edition_lookup ON ayah_edition(ayah_id, edition_id);

CREATE OR REPLACE VIEW surah_stats AS
SELECT s.id, s.name_ar, s.name_en, s.name_en_translation, s.type,
       COUNT(a.id) as ayat_count,
       MIN(a.id) as start_ayah_id,
       MAX(a.id) as end_ayah_id
FROM surahs s
JOIN ayahs a ON a.surah_id = s.id
GROUP BY s.id;

CREATE OR REPLACE VIEW ayah_with_translation AS
SELECT a.id, a.surah_id, a.number_in_surah, a.text as arabic,
       ae.data as translation, e.language, e.name as edition_name
FROM ayahs a
JOIN ayah_edition ae ON ae.ayah_id = a.id
JOIN editions e ON e.id = ae.edition_id;
