#!/usr/bin/env python3
"""
Write readable schema references to schema/<database>/schema.sql.

The converters hold the authoritative DDL for the enriched SQLite and
PostgreSQL models, and the MySQL dump holds the source model. Nobody should
have to read Python or unzip 187 MB to see the shape of the data, so this
regenerates all three as plain SQL.

    python3 scripts/export_schema.py

CI regenerates and then fails on any diff, so an edit to a converter that is
not reflected here cannot land. Edit the converter, never the output.

Standard library only.
"""

from __future__ import annotations

import ast
import re
import textwrap
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DUMP = ROOT / "data" / "quran.sql.zip"

BANNER = (
    "-- Generated by scripts/export_schema.py — do not edit.\n"
    "-- Source of truth: {source}\n"
)

CREATE = re.compile(r"\bCREATE\s+(TABLE|INDEX|OR\s+REPLACE\s+VIEW|VIEW)\b", re.I)


def ddl_from_converter(path: Path) -> str:
    """Pull the CREATE statements out of a converter without importing it.

    Reading the source rather than executing it means this works with no
    database, no psycopg2, and no 187 MB dump on disk.
    """
    tree = ast.parse(path.read_text())
    statements: list[str] = []

    for node in ast.walk(tree):
        if not (isinstance(node, ast.Constant) and isinstance(node.value, str)):
            continue
        block = textwrap.dedent(node.value).strip()
        if not CREATE.search(block):
            continue
        # A block may hold several statements; keep only the creating ones so
        # the reference does not open with a wall of DROP TABLE.
        for statement in (s.strip() for s in block.split(";")):
            if statement and CREATE.match(statement):
                statements.append(statement + ";")

    return "\n\n".join(statements) + "\n"


def ddl_from_dump() -> str:
    """Extract the source MySQL schema by streaming the zip, skipping INSERTs.

    The dump interleaves DDL with 835,624 rows of data and closes with the
    ALTER TABLE statements that add keys, so the whole member has to be read —
    but never all at once, and never onto disk.
    """
    lines: list[str] = []
    skipping = False

    with zipfile.ZipFile(DUMP) as archive, archive.open("quran.sql") as handle:
        for raw in handle:
            line = raw.decode("utf-8").rstrip("\n")
            if skipping:
                skipping = not line.endswith(";")
                continue
            if line.startswith("INSERT INTO"):
                skipping = not line.endswith(";")
                continue
            if line.startswith(("--", "/*", "SET ", "START ", "COMMIT")) or not line.strip():
                continue
            lines.append(line)

    return "\n".join(lines) + "\n"


def write(relative: str, source: str, body: str) -> None:
    target = ROOT / "schema" / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(BANNER.format(source=source) + "\n" + body)
    print(f"wrote {target.relative_to(ROOT)} ({len(body.splitlines())} lines)")


def main() -> None:
    write("sqlite/schema.sql", "convert_to_sqlite.py",
          ddl_from_converter(ROOT / "convert_to_sqlite.py"))
    write("postgres/schema.sql", "convert_to_postgres.py",
          ddl_from_converter(ROOT / "convert_to_postgres.py"))
    write(
        "mysql/schema.sql",
        "data/quran.sql.zip",
        "-- The source dump came from a Laravel application, so users,\n"
        "-- password_resets, and migrations appear below. They hold no data worth\n"
        "-- importing and both converters skip them; see docs/architecture.md.\n\n"
        + ddl_from_dump(),
    )


if __name__ == "__main__":
    main()
